name: emberquest
description: Simple platform game.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.8.2
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/
